name: CI/CD Pipeline for Carnicería

on:
  push:
    branches: [ "DEV-QA" ]
  pull_request:
    branches: [ "DEV-QA" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'maven'
    
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - name: Run Unit Tests
      run: mvn -B test
      
    - name: Run Integration Tests
      run: mvn -B verify -DskipUnitTests=true
      env:
        SPRING_DATASOURCE_URL: jdbc:h2:mem:testdb
        SPRING_DATASOURCE_USERNAME: sa
        SPRING_DATASOURCE_PASSWORD:
        SPRING_JPA_HIBERNATE_DDL-AUTO: create-drop

    - name: Upload Test Reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-reports
        path: |
          **/target/surefire-reports
          **/target/failsafe-reports
          **/target/jacoco

    - name: Upload Code Coverage
      uses: codecov/codecov-action@v4
      if: success()
    
  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/DEV-QA'

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Deploy to Production via FTP
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      if: success()
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: target/
        server-dir: /public_html/carniceria/

    - name: Merge DEV-QA to MAIN
      if: success()
      uses: devmasx/merge-branch@v1.4.0
      with:
        type: now
        from_branch: DEV-QA
        target_branch: main
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Send Email Notification
      if: always()
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: ${{ job.status }} - CI/CD Pipeline Result for Carnicería
        to: ${{ secrets.EMAIL_RECIPIENT }}
        from: GitHub Actions
        body: |
          The CI/CD pipeline for Carnicería has completed with status: ${{ job.status }}.
          View the logs here: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}